controller_manager:
  ros__parameters:
    update_rate: 50  # Hz (T: 50ms)
    use_sim_time: false

    edie_diff_drive_controller:
      type: edie_diff_drive_controller/DiffDriveController

    edie_l_leg_position_controller:
      type: position_controllers/JointGroupPositionController

    edie_r_leg_position_controller:
      type: position_controllers/JointGroupPositionController

    edie_l_ear_position_controller:
      type: position_controllers/JointGroupPositionController

    edie_r_ear_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

edie_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    wheel_separation: 0.136
    wheel_radius: 0.05

    use_stamped_vel: false
    enable_odom_tf: false
    position_feedback: true
    open_loop: false
    ideal_pose: true

edie_l_leg_position_controller:
  ros__parameters:
    joints:
      - left_leg_joint

edie_r_leg_position_controller:
  ros__parameters:
    joints:
      - right_leg_joint

edie_l_ear_position_controller:
  ros__parameters:
    joints:
      - left_ear_joint

edie_r_ear_position_controller:
  ros__parameters:
    joints:
      - right_ear_joint

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 40.0  # Hz
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - left_ear_joint 
      - right_ear_joint
      - left_leg_joint
      - right_leg_joint
