Point1_x : -0.10
Point1_y : 0.2
Point1_theta : 1.5708

Point2_x : -0.10
Point2_y : 1.65
Point2_theta : 1.5708

Point3_x : 0
Point3_y : 0.6
Point3_theta : 1.5708

Point4_x : 0
Point4_y : 1.6
Point4_theta : 1.5708
