alpha1: 0.5                   # 0.01 -> 0.1 -> (Apr 14) 0.5 -> (Apr 15) 0.2
alpha2: 1.0                   # 0.01 -> 0.1 -> (Apr 14) 0.5 -> (Apr 15) 0.01
alpha3_x: 0.3                 # 0.1 -> (Apr 11) 0.5
alpha3_y: 0.3                 # 0.1 -> (Apr 14) 0.5
# ---No use----
alpha3: 0.0
# -------------
alpha4: 0.4                  # 0.01 -> 0.1
translation_threshold: 0.001  # 0.01 -> 0.0045